## Quiz

In [1]:
from bs4 import BeautifulSoup
import os
import pandas as pd

In [2]:
# List of dictionaries to build file by file and later convert to a DataFrame
df_list = []
folder = 'rt_html'
for movie_html in os.listdir(folder):
    with open(os.path.join(folder, movie_html)) as file:
        soup=BeautifulSoup(file)
        title=soup.find('title').contents[0][: -len('- Rotten Tomatoes')]
        # Note: a correct implementation may take ~15 seconds to run
        #print(title)
        #break
        audience_score=soup.find('div', class_='audience-score meter').find('span').contents[0][:-1]
        num_audience_rating=soup.find('div',class_='audience-info hidden-xs superPageFontColor')
        #print(num_audience_rating)
        num_audience_rating=num_audience_rating.find_all('div')[1].contents[2].strip().replace(',','')
        #print(num_audience_rating)
        #break
        df_list.append({'title': title,'audience_score':int(audience_score),'num_audience_rating':int(num_audience_rating)})
df=pd.DataFrame(df_list,columns=['title','audience_score','num_audience_rating'])

/opt/conda/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file /opt/conda/lib/python3.6/runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))

In [4]:
df

,title,audience_score,num_audience_rating
0,Dr. Strangelove Or How I Learned to Stop Worry...,94,208215
1,Frankenstein (1931),87,41140
2,All About Eve (1950),94,44564
3,Roman Holiday (1953),94,62895
4,The Night of the Hunter (1955),90,24322
5,Toy Story (1995),92,1107731
6,The Treasure of the Sierra Madre (1948),93,25627
7,Skyfall (2012),86,372497
8,The Wrestler (2008),88,139795
9,Star Trek (2009),91,746458
10,The Dark Knight (2008),94,1827436
11,The Adventures of Robin Hood (1938),89,33584
12,The Wages of Fear (1953),95,8536
13,Rosemary's Baby (1968),87,72669
14,The Cabinet of Dr. Caligari (Das Cabinet des D...,89,27163
15,L.A. Confidential (1997),94,149772
16,Star Wars: Episode VII - The Force Awakens (20...,89,222789
17,Army of Shadows (L'Armée des ombres) (1969),94,7011
18,Rashômon (1951),93,47657
19,Pinocchio (1940),72,278682
20,Repulsion (1965),87,18655
21,Jaws (1975),90,942217
22,The Wizard of Oz (1939),89,874425
23,The 400 Blows (Les Quatre cents coups) (1959),94,38368
24,Hell or High Water (2016),88,37738
25,La La Land (2016),82,67325
26,Manchester by the Sea (2016),77,48189
27,Harry Potter and the Deathly Hallows - Part 2 ...,89,389431
28,High Noon (1952),89,25065
29,Taxi Driver (1976),93,258405
...,...,...,...
70,The Babadook (2014),72,37024
71,The Grapes of Wrath (1940),88,23954
72,It Happened One Night (1934),93,33106
73,The Big Sick (2017),90,23391
74,On the Waterfront (1954),95,51664
75,Singin' in the Rain (1952),95,137643
76,Man on Wire (2008),87,29827
77,La Grande illusion (Grand Illusion) (1938),92,11490
78,Open City (1946),92,6128
79,Snow White and the Seven Dwarfs (1937),78,469510
80,Rear Window (1954),95,149458
81,M (1931),95,35778
82,Brooklyn (2015),87,45763
83,Toy Story 2 (1999),86,998186
84,The 39 Steps (1935),86,23647
85,Finding Nemo (2003),86,33355673
86,Psycho (1960),94,238259
87,E.T. The Extra-Terrestrial (1982),72,32313030
88,Metropolis (1927),92,62018
89,The Battle of Algiers (La Battaglia di Algeri)...,95,14267
90,The Bride of Frankenstein (1935),87,24471
91,A Hard Day's Night (1964),89,50067
92,Touch of Evil (1958),92,30867
93,"The Good, the Bad and the Ugly (1966)",97,238420
94,Vertigo (1958),93,101454
95,"The Godfather, Part II (1974)",97,409574
96,Up (2009),90,1201878
97,The Jungle Book (2016),86,92856
98,Get Out (2017),87,63837
99,King Kong (1933),86,89669

## Solution Test
Run the cell below the see if your solution is correct. If an `AssertionError` is thrown, your solution is incorrect. If no error is thrown, your solution is correct.

In [6]:
df_solution = pd.read_pickle('df_solution.pkl')
df.sort_values('title', inplace = True)
df.reset_index(inplace = True, drop = True)
df_solution.sort_values('title', inplace = True)
df_solution.reset_index(inplace = True, drop = True)
pd.testing.assert_frame_equal(df, df_solution)

AssertionError: DataFrame.columns are different

DataFrame.columns values are different (33.33333 %)
[left]:  Index(['title', 'audience_score', 'num_audience_rating'], dtype='object')
[right]: Index(['title', 'audience_score', 'number_of_audience_ratings'], dtype='object')